services:
  floci:
    image: floci/floci:latest
    container_name: floci
    ports:
      - "4566:4566"
    environment:
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - floci_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./frontend
    container_name: frontend-dashboard
    ports:
      - "8080:80"
    networks:
      - evaluacion2_default
      
  postgres:
    image: postgres:15
    container_name: catalogo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogoProductos

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  floci_data: